apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq-deployment
  name:  rabbitmq-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:latest
        imagePullPolicy: Always
        name: rabbitmq-container
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "1Gi"
            cpu: "2000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}