apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  namespace: mongo-cluster
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
   path: /data/mongo