apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  namespace: mongo-cluster
spec:
  storageClassName: ""
  resources:
    requests:
       storage: 2Gi
  volumeMode: Filesystem
  volumeName: pv-mongo
  accessModes:
    - ReadWriteOnce