---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-svc
  namespace: mongo-cluster
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongo-peer-discovery-rbac
  namespace: mongo-cluster
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongo-peer-discovery-rbac
  namespace: mongo-cluster
subjects:
- kind: ServiceAccount
  name: mongo-svc
  namespace: mongo-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongo-peer-discovery-rbac
